version: '3.4'

services:
  rest-spring-boot-kotlin-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest-spring-boot-kotlin-db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    networks:
      - spring-rest_example
networks:
  spring-rest_example:
    driver: bridge
