spring:
  datasource:
    url: jdbc:h2:mem:rest-spring-boot-kotlin-db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

