apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: springbootapp

images:
- name: springbootapp
  newName: asan2019/argocd-example
  newTag: 9019444af41434427a9ba308476aaf4b20d0854a
